/**
 * Product copy that must outlive the mock layer.
 *
 * These strings are shown next to AI output and written into the downloadable
 * report, so they are part of the product, not part of the fixtures. Phase 3
 * removed the mock layer — no test double may own text the UI still needs.
 */

/** Shown with every AI response in the UI. */
export const AI_DISCLOSURE =
  'This response was generated by AI and may contain errors. It is general information, not regulated financial advice. Verify anything important before acting on it.';

/** Written into the statement workbook itself, which outlives the screen. */
export const AI_REPORT_DISCLAIMER =
  'This report includes AI-generated content. Figures are derived from the statement you uploaded and may contain errors. Verify against your bank records before acting on them.';
